// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: datetime.proto

package protos

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DatetimeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datetime *timestamp.Timestamp `protobuf:"bytes,1,opt,name=datetime,proto3" json:"datetime,omitempty"`
}

func (x *DatetimeResponse) Reset() {
	*x = DatetimeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_datetime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DatetimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatetimeResponse) ProtoMessage() {}

func (x *DatetimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_datetime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatetimeResponse.ProtoReflect.Descriptor instead.
func (*DatetimeResponse) Descriptor() ([]byte, []int) {
	return file_datetime_proto_rawDescGZIP(), []int{0}
}

func (x *DatetimeResponse) GetDatetime() *timestamp.Timestamp {
	if x != nil {
		return x.Datetime
	}
	return nil
}

var File_datetime_proto protoreflect.FileDescriptor

var file_datetime_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4a,
	0x0a, 0x10, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x32, 0x39, 0x0a, 0x03, 0x4e, 0x6f,
	0x77, 0x12, 0x32, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x11, 0x2e, 0x44, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x69, 0x73, 0x74, 0x61, 0x74, 0x69, 0x75, 0x6d, 0x2f, 0x72, 0x65,
	0x5f, 0x61, 0x72, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_datetime_proto_rawDescOnce sync.Once
	file_datetime_proto_rawDescData = file_datetime_proto_rawDesc
)

func file_datetime_proto_rawDescGZIP() []byte {
	file_datetime_proto_rawDescOnce.Do(func() {
		file_datetime_proto_rawDescData = protoimpl.X.CompressGZIP(file_datetime_proto_rawDescData)
	})
	return file_datetime_proto_rawDescData
}

var file_datetime_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_datetime_proto_goTypes = []interface{}{
	(*DatetimeResponse)(nil),    // 0: DatetimeResponse
	(*timestamp.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*empty.Empty)(nil),         // 2: google.protobuf.Empty
}
var file_datetime_proto_depIdxs = []int32{
	1, // 0: DatetimeResponse.datetime:type_name -> google.protobuf.Timestamp
	2, // 1: Now.Get:input_type -> google.protobuf.Empty
	0, // 2: Now.Get:output_type -> DatetimeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_datetime_proto_init() }
func file_datetime_proto_init() {
	if File_datetime_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_datetime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DatetimeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_datetime_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_datetime_proto_goTypes,
		DependencyIndexes: file_datetime_proto_depIdxs,
		MessageInfos:      file_datetime_proto_msgTypes,
	}.Build()
	File_datetime_proto = out.File
	file_datetime_proto_rawDesc = nil
	file_datetime_proto_goTypes = nil
	file_datetime_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NowClient is the client API for Now service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NowClient interface {
	Get(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*DatetimeResponse, error)
}

type nowClient struct {
	cc grpc.ClientConnInterface
}

func NewNowClient(cc grpc.ClientConnInterface) NowClient {
	return &nowClient{cc}
}

func (c *nowClient) Get(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*DatetimeResponse, error) {
	out := new(DatetimeResponse)
	err := c.cc.Invoke(ctx, "/Now/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NowServer is the server API for Now service.
type NowServer interface {
	Get(context.Context, *empty.Empty) (*DatetimeResponse, error)
}

// UnimplementedNowServer can be embedded to have forward compatible implementations.
type UnimplementedNowServer struct {
}

func (*UnimplementedNowServer) Get(context.Context, *empty.Empty) (*DatetimeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}

func RegisterNowServer(s *grpc.Server, srv NowServer) {
	s.RegisterService(&_Now_serviceDesc, srv)
}

func _Now_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NowServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Now/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NowServer).Get(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Now_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Now",
	HandlerType: (*NowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Now_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datetime.proto",
}
